apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mdm-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mdm-service
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: mdm-service
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: mdm-service
    spec:
      serviceAccountName: {{ include "mdm-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mdmservice
      containers:
        - name: mdm-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8092
          volumeMounts:
            - name: data
              mountPath: /var/opt
          env:
            - name: DB_HOST
              value: 172.16.200.107:3306
            - name: DB_NAME
              value: mdm 
            - name: DB_USERNAME
              value: aduser
            - name: DB_PASSWORD
              value: aduser
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
