apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdmservice
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi