apiVersion: v1
kind: Service
metadata:
  name: {{ include "mdm-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mdm-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8092
      name: http
  selector:
    app: mdm-service
  type: {{ .Values.service.type }}
